//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioASFI
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cuenta", Namespace="http://tempuri.org/")]
    public partial class Cuenta : object
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioASFI.ServicioASFISoap")]
    public interface ServicioASFISoap
    {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ci del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaCuentas", ReplyAction="*")]
        ServicioASFI.ConsultaCuentasResponse ConsultaCuentas(ServicioASFI.ConsultaCuentasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaCuentas", ReplyAction="*")]
        System.Threading.Tasks.Task<ServicioASFI.ConsultaCuentasResponse> ConsultaCuentasAsync(ServicioASFI.ConsultaCuentasRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaCuentasRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaCuentas", Namespace="http://tempuri.org/", Order=0)]
        public ServicioASFI.ConsultaCuentasRequestBody Body;
        
        public ConsultaCuentasRequest()
        {
        }
        
        public ConsultaCuentasRequest(ServicioASFI.ConsultaCuentasRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultaCuentasRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ci;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nombres;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Apellidos;
        
        public ConsultaCuentasRequestBody()
        {
        }
        
        public ConsultaCuentasRequestBody(string ci, string nombres, string Apellidos)
        {
            this.ci = ci;
            this.nombres = nombres;
            this.Apellidos = Apellidos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaCuentasResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaCuentasResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServicioASFI.ConsultaCuentasResponseBody Body;
        
        public ConsultaCuentasResponse()
        {
        }
        
        public ConsultaCuentasResponse(ServicioASFI.ConsultaCuentasResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultaCuentasResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServicioASFI.Cuenta[] ConsultaCuentasResult;
        
        public ConsultaCuentasResponseBody()
        {
        }
        
        public ConsultaCuentasResponseBody(ServicioASFI.Cuenta[] ConsultaCuentasResult)
        {
            this.ConsultaCuentasResult = ConsultaCuentasResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface ServicioASFISoapChannel : ServicioASFI.ServicioASFISoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ServicioASFISoapClient : System.ServiceModel.ClientBase<ServicioASFI.ServicioASFISoap>, ServicioASFI.ServicioASFISoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioASFISoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioASFISoapClient.GetBindingForEndpoint(endpointConfiguration), ServicioASFISoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioASFISoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioASFISoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioASFISoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioASFISoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioASFISoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServicioASFI.ConsultaCuentasResponse ServicioASFI.ServicioASFISoap.ConsultaCuentas(ServicioASFI.ConsultaCuentasRequest request)
        {
            return base.Channel.ConsultaCuentas(request);
        }
        
        public ServicioASFI.Cuenta[] ConsultaCuentas(string ci, string nombres, string Apellidos)
        {
            ServicioASFI.ConsultaCuentasRequest inValue = new ServicioASFI.ConsultaCuentasRequest();
            inValue.Body = new ServicioASFI.ConsultaCuentasRequestBody();
            inValue.Body.ci = ci;
            inValue.Body.nombres = nombres;
            inValue.Body.Apellidos = Apellidos;
            ServicioASFI.ConsultaCuentasResponse retVal = ((ServicioASFI.ServicioASFISoap)(this)).ConsultaCuentas(inValue);
            return retVal.Body.ConsultaCuentasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServicioASFI.ConsultaCuentasResponse> ServicioASFI.ServicioASFISoap.ConsultaCuentasAsync(ServicioASFI.ConsultaCuentasRequest request)
        {
            return base.Channel.ConsultaCuentasAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioASFI.ConsultaCuentasResponse> ConsultaCuentasAsync(string ci, string nombres, string Apellidos)
        {
            ServicioASFI.ConsultaCuentasRequest inValue = new ServicioASFI.ConsultaCuentasRequest();
            inValue.Body = new ServicioASFI.ConsultaCuentasRequestBody();
            inValue.Body.ci = ci;
            inValue.Body.nombres = nombres;
            inValue.Body.Apellidos = Apellidos;
            return ((ServicioASFI.ServicioASFISoap)(this)).ConsultaCuentasAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServicioASFISoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ServicioASFISoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServicioASFISoap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:53268/ServicioASFI.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.ServicioASFISoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:53268/ServicioASFI.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ServicioASFISoap,
            
            ServicioASFISoap12,
        }
    }
}
